apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: observability-demo-rules
  namespace: observability-demo
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: observability-demo.slo
      rules:
        - alert: DemoApiHighErrorRate
          expr: |
            sum(rate(demo_http_requests_total{status=~"5.."}[5m]))
            /
            clamp_min(sum(rate(demo_http_requests_total[5m])), 0.001)
            > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Demo API error rate is above 5%
            description: More than 5% of requests have returned 5xx for 5 minutes.
        - alert: DemoApiHighP95Latency
          expr: |
            histogram_quantile(
              0.95,
              sum by (le) (rate(demo_http_request_duration_seconds_bucket[5m]))
            ) > 0.5
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Demo API p95 latency is above 500ms
            description: The p95 application latency has exceeded the lab SLO for 10 minutes.
