grafana:
  enabled: true
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        derivedFields:
          - name: TraceID
            matcherRegex: 'trace_id[=: ]+([a-fA-F0-9]+)'
            datasourceUid: tempo
            url: '$${__value.raw}'
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3100
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
        serviceMap:
          datasourceUid: prometheus
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d
alertmanager:
  enabled: true
